baseURL: 'https://xorkevin.dev/'
languageCode: 'en-us'
title: 'xorkevin.dev'
theme: 'compass'
pluralizelisttitles: 'false'
copyright: 2019
uglyurls: true
permalinks:
  gomod: '/:filename'
params:
  gomodroot: 'xorkevin.dev'
